### ISSUE TITLE
special scrollbar 

### ISSUE THREAD

**Issue by VinayLodhi1712** [arjunatapadkar/codeteria#1]
![scrollbar2](https://github.com/user-attachments/assets/2bc0a805-7e9a-4beb-bfd4-3d9c138a0bb2)
 
The side scroll bar is not looking good on website I want to make it good UI like this below video with your website suited colour.

https://github.com/user-attachments/assets/1bf03051-7f38-415f-ae6e-eb617dbd3550

**Comment by arjunatapadkar** [comment]
Looks great 👍

**Comment by VinayLodhi1712** [comment]
> Looks great 👍

I am working on this but can you also help me by assigning this issue under gssoc extended and hactoberfest tag, so it will help me too.

**Comment by VinayLodhi1712** [comment]
hello sir @arjunatapadkar can you plz add level in it so it will be help me to add PR on gssoc leaderboard, this PR is not showing there because on no level add on it
