### ISSUE TITLE
Make footer consistent 

### ISSUE THREAD

**Issue by arjunatapadkar** [arjunatapadkar/codeteria#107]
The home page footer should be inside one component and it should be implemented in all the pages across website

PR should be with the video of changes made

**Comment by sabbirhosen44** [comment]
Hello @arjunatapadkar ,

I would like to take on the task of refactoring the homepage footer into a single component and implementing it across all pages of the website. This will help ensure consistency and make future updates to the footer easier to manage.

As part of the pull request, I will include a video demonstrating the changes made for better visibility and review.

Thank you for considering my request. I look forward to contributing to this improvement.

**Comment by SaanyaGarg5** [comment]
You can assign me this task ..

**Comment by Md-SabbirHosen** [comment]
@arjunatapadkar I'm currently working on this issue.  Please give me some time

**Comment by arjunatapadkar** [comment]
@Md-SabbirHosen create PR asap

**Comment by SaanyaGarg5** [comment]
@arjunatapadkar   do i have to work on it?

**Comment by arjunatapadkar** [comment]
@SaanyaGarg5 PR will be merged on first come first serve basis

**Comment by coder-writes** [comment]
Hey @arjunatapadkar, hey here for #125(the same issue) please assign me this issue under the labels "GSSoC-Extd'24" and "Hacktoberfest'24" to make my contribution count.

**Comment by SaanyaGarg5** [comment]
I have submitted my work u can check

**Comment by arjunatapadkar** [comment]
It's not accurate

**Comment by coder-writes** [comment]
hey @arjunatapadkar  , Do I also have to change the footer or implement the footer of the homepage across all the pages ?

**Comment by itznayan** [comment]
@arjunatapadkar please assign this task to me.
