### ISSUE TITLE
Add System Design Concepts

### ISSUE THREAD

**Issue by J-B-Mugundh** [arjunatapadkar/codeteria#108]
I would like to contribute on adding basic concepts of System design along with example (Either Code or Image). 

Main Concepts include:

- Network Protocols
- Load Balancing
- Memcaching
- Performance vs Scalability
- Latency vs Throughput
- Availability vs Consistency
- CAP Theorem, etc.

**Comment by J-B-Mugundh** [comment]
@arjunatapadkar Hi! I'm good with basic System design concepts and very much interested in the same. So, I would like to contribute on this section. I'm a gssoc-extd and hacktoberfest contributor. Please add the respective labels and assign level 3 as the content I would provide here would be a really best one and easy to understand.

**Comment by J-B-Mugundh** [comment]
@arjunatapadkar Could u tell me how I could add this since there's no backend code present? Can I make use of a json file to load the content and data? Or could you please let me know your expectations on which format could be best suitable for our project?

**Comment by arjunatapadkar** [comment]
there is  backend but its not under gssoc its private repository, you can create json file and will then add to the database

**Comment by J-B-Mugundh** [comment]
> there is backend but its not under gssoc its private repository, you can create json file and will then add to the database

Okay! If the DB schema is designed already for this section, could u share me how it should be?

**Comment by arjunatapadkar** [comment]
No it's not yet designed, but create it in a way that it should be easy to move to db
