### ISSUE TITLE
Addition of links to icons and change of color on hovering the icons

### ISSUE THREAD

**Issue by Shirisha-16** [arjunatapadkar/codeteria#110]
Addition of links to icons 
Change or highlighting on hovering the icons.
![Screenshot 2024-10-09 180112](https://github.com/user-attachments/assets/4be98602-0cf2-458f-8367-d0029e61e4e0)
I want to work on this issue
@arjunatapadkar assign me this work with the labels gssoc-ext, hacktoberfest-accepted and level according to the issue.

**Comment by SaanyaGarg5** [comment]
You can assign me this task under gsssoc and hacktoberfest level 3 label.
