### ISSUE TITLE
Adding Back to home button in not found page 

### ISSUE THREAD

**Issue by G-Rajashekar** [arjunatapadkar/codeteria#111]
Adding back to home button in not found page will enhance the user experience
<img width="857" alt="image" src="https://github.com/user-attachments/assets/92c6edcc-6d1c-4308-9689-6fe7209472c9">

**Comment by G-Rajashekar** [comment]
can you assign this issue to me with labels gssoc-ext and hacktoberfest

**Comment by kaurpreetman** [comment]
can you assign this issue to me with labels gssoc-ext and hacktoberfest
