### ISSUE TITLE
Adding home link to website logo in the footer section

### ISSUE THREAD

**Issue by G-Rajashekar** [arjunatapadkar/codeteria#112]
When user clicked on website logo which is on the footer section it is not navigating to the home section.
It will look good if we add this feature
<img width="251" alt="image" src="https://github.com/user-attachments/assets/7fee9037-a5fd-4a93-aeb3-88b94eda2ed7">

**Comment by kaurpreetman** [comment]
can you assign this issue to me with labels gssoc-ext and hacktoberfest
