### ISSUE TITLE
Proposal to "Standardize Header and Footer" for Codeteria Website

### ISSUE THREAD

**Issue by clownfish1805** [arjunatapadkar/codeteria#12]
@arjunatapadkar 
I would like to create a **similar header and footer for this website Codeteria**. 
**Issue:**  Currently, the home page has a different header and footer compared to the "Start Coding" page, which disrupts the visual consistency.

**Home page header footer:**
![image](https://github.com/user-attachments/assets/5da3aa3e-24ca-4b65-add2-9189fba24253)
![image](https://github.com/user-attachments/assets/01c9953a-a135-457c-9cea-9435c2021a89)

**Different header footer:**
![image](https://github.com/user-attachments/assets/63ce5023-289b-4c08-aecb-fb83d0cbb040)
![image](https://github.com/user-attachments/assets/45c89a6c-d30a-4572-861a-16d4bca132af)

**My Plan:**
1. Create a **consistent header and footer** for both pages to ensure a unified look.
2. Add the **Codeteria logo** to the navigation on the other pages for branding consistency.

Please assign me this issue for GSSOC'24 extended with the required labels.

**Comment by arjunatapadkar** [comment]
@clownfish1805  After completing make sure to show before and after snapshots to get pr merged quickly

**Comment by clownfish1805** [comment]
@arjunatapadkar I have raised PR for this issue. Kindly check.
