### ISSUE TITLE
Improve Footer Visibility content to same color of the text and background of challenges page 

### ISSUE THREAD

**Issue by coder-writes** [arjunatapadkar/codeteria#125]
Currently, the footer text and elements on the website are displayed in white. While this works on a light background, the text becomes invisible when switching to a dark background. I would like to work on adjusting the text colors and styling to ensure they remain visible and user-friendly when the background color is set to black or dark shades. This will enhance the accessibility and overall user experience on the website. Kindly assign this issue to me so I can begin making the necessary adjustments.

Let me know if you'd like any adjustments!

![Screenshot 2024-10-11 115530](https://github.com/user-attachments/assets/8368c329-c70b-4de2-9c46-bda9b68715d4)

**Comment by arjunatapadkar** [comment]
You can work on issue #107 @coder-writes

**Comment by coder-writes** [comment]
Hey @arjunatapadkar, please assign me this issue under the labels "GSSoC-Extd'24" and "Hacktoberfest'24" to make the contribution count.

**Comment by arjunatapadkar** [comment]
Comment in that issue #107  for assignment
