### ISSUE TITLE
Animated Cursor

### ISSUE THREAD

**Issue by itznayan** [arjunatapadkar/codeteria#131]
Current Cursor look annoying not .its create bad UX. i would like to implement custom cursor which match theme of website.

**Comment by aniketmdinde** [comment]
Can you assign me this issue? I would like to work on it.

**Comment by Bhumika-00** [comment]
Can you assign this issue to me... please I really need that @aniketmdinde @arjunatapadkar @itznayan @KumarAmrendram @medakshchoudhary

**Comment by itznayan** [comment]
@arjunatapadkar please approved PR.
