### ISSUE TITLE
Add User Profile Page (Frontend Only)

### ISSUE THREAD

**Issue by ayan0xdl** [arjunatapadkar/codeteria#137]
**Features:**

  - Display fields for **Username**, **Email**, and **Profile Picture** (with local preview functionality).
  - Add fields for **Full Name**, **Short Bio** (like a coding mantra or favorite programming quote), and links to **social media profiles** (GitHub, LinkedIn, etc.).
  - Allow users to apply a **pixel-art filter** or coder-themed overlay to their profile picture.
  - Enable selection of a **programmatically generated avatar** based on their username or favorite programming language.
  - Show **coding stats** (e.g., lines of code written, favorite programming languages).
  - Implement a **badge system** with achievements such as “First Code Snippet,” “Regex Master,” etc.
  - Allow users to showcase **code snippets** with syntax highlighting on their profile page.
  - Ensure **responsive design** for seamless use across all devices.

**Comment by arjunatapadkar** [comment]
you can build it but will see the result first and then decide whether it should be merged or not, use the standard file structure while creating the page.
