### ISSUE TITLE
🌟 Feature: Add a Scroll "Progress Indicator Bar" 

### ISSUE THREAD

**Issue by Tejashri-Taral** [arjunatapadkar/codeteria#154]
Hey @arjunatapadkar ,
I want to add a "Scroll Down Progress Bar"
This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page.
The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.
****screenshot****
![345564483-96dbad41-dabb-48c0-a41e-dcdadb040b3b](https://github.com/user-attachments/assets/d3f25b7b-e6b4-475a-bae2-c864acc4b89e)

Can you please assign it to me?

**Comment by Tejashri-Taral** [comment]
@arjunatapadkar

**Comment by sriharsha0x1** [comment]
could you please assign this task to me ? @arjunatapadkar
