### ISSUE TITLE
Readme.md file 

### ISSUE THREAD

**Issue by arjunatapadkar** [arjunatapadkar/codeteria#17]

**Comment by Charul00** [comment]
can you please assign to me

**Comment by arjunatapadkar** [comment]
@Charul00 do it quickly otherwise will assign the issue to someone else

**Comment by rajatsinghal02** [comment]
@arjunatapadkar Please assign this issue to me . I have created the file as fast as you assigned me. I have good knowledge of creating Good Readme.md files.

**Comment by arjunatapadkar** [comment]
Will merge the pr which is more accurate and visually appealing

**Comment by rajatsinghal02** [comment]
@arjunatapadkar Assign this issue to me to work in this issue.

**Comment by anupkushwaha8081** [comment]
i am interse

**Comment by jaidh01** [comment]
@arjunatapadkar I would like to work on this issue.
Please assign this issue to me.
I will update the readme file into something like this and I will also add the contributors profile photo in this : -

![Screenshot (42)](https://github.com/user-attachments/assets/366a8fa6-f48d-48ac-a4cd-9cc413f96fd5)

**Comment by jaidh01** [comment]
Hi @arjunatapadkar,
I request you to please add the `hacktoberfest-accepted` label, to this issue.

Thank you for your time!
