### ISSUE TITLE
Enhance Footer with Hover Effects and 3D Animation for Social Media Icons

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [arjunatapadkar/codeteria#181]
# Issue Description:
I have noticed that the footer logo lacks any hover effect or animation, and the footer items do not have any attractive animations. I want to implement hover effects for the footer items to improve their visual appeal. Additionally, I would like to add a 3D hover effect to the social media icons to make them more engaging. This enhancement aims to create a more interactive and visually appealing footer for the website.

---
# Screenshot
![footer2 0](https://github.com/user-attachments/assets/1e53ea5d-72d9-453a-a73c-072903e77772)

**Comment by amanreddy77** [comment]
hwy @biswajit-sarkar-007 can I take this up ?
