### ISSUE TITLE
Adding Newsletter Subscription

### ISSUE THREAD

**Issue by AswaniBolisetti** [arjunatapadkar/codeteria#189]
@arjunatapadkar 
I would like to add Newsletter Subscription section
Could you please assign it to me

**Comment by meghanakn473** [comment]
@arjunatapadkar please assign this issue to me i would finish it by evening, as there is no response from @AswaniBolisetti

**Comment by AswaniBolisetti** [comment]
@meghanakn473 
Sorry, but i completed this

@arjunatapadkar 
Could you please close this issue
