### ISSUE TITLE
Set Up Complete Backend with MongoDB for Login and Signup Features

### ISSUE THREAD

**Issue by krishkishore972** [arjunatapadkar/codeteria#2]
We need to set up a complete backend system using MongoDB to implement the login and signup features for our application. This backend will handle user authentication, data storage, and ensure secure access to user accounts.

-Objectives :

1. Establish a connection to the MongoDB database.
2. Implement user registration (signup) functionality.
3. Implement user authentication (login) functionality
4. Set up necessary API endpoints for handling login and signup requests

 This is a very primary issue and mark it as level 3 or give higher point for contribution if possible

**Comment by arjunatapadkar** [comment]
There is a independent repository for backend and it is not under gssoc
