### ISSUE TITLE
Login & sign up page 

### ISSUE THREAD

**Issue by meghanakn473** [arjunatapadkar/codeteria#202]
i want to implemeent login and sign up page to help users create their own accounts and learn

@arjunatapadkar please assign me this issue i want to work on it and also add level3,gssoc-extd and hacktoberfest labels

**Comment by Mrigank118** [comment]
Hi! I’m a MERN stack developer, and I would love to implement the login and signup pages for this project. This feature will help users create their own accounts, offering a smoother onboarding experience and allowing them to learn and interact with the platform. I have experience building authentication systems and can ensure secure and efficient functionality. Please assign this task to me, and I’ll get started on it right away!
