### ISSUE TITLE
[enhancement]: Light mode and Dark mode toggle

### ISSUE THREAD

**Issue by faiz66388** [arjunatapadkar/codeteria#209]
Description:
A toggle feature for switching between light mode and dark mode is required for better accessibility and user experience. Implementing this would allow users to choose between themes according to their preferences or environment.

Steps to Reproduce:
Navigate to the application.
Look for theme settings or a toggle for light/dark mode.
Notice the absence of this functionality.
Expected Behavior:
A toggle button should be available, allowing users to switch between light and dark themes seamlessly. The application should remember the user's theme preference across sessions.

Actual Behavior:
Currently, there is no option to switch between light and dark modes.

Screenshots/Logs:
![Screenshot 2024-10-20 203334](https://github.com/user-attachments/assets/ae3e7696-0971-4f2c-ac7f-e16271c8dd0a)

**Comment by Mrigank118** [comment]
Hi! I’m a MERN stack developer with experience in building accessible and user-friendly applications. I’ve implemented light/dark mode toggle features in several projects before, ensuring smooth theme switching that enhances both user experience and accessibility. I would love to take on this task and implement a reliable toggle feature for your application. Please assign this issue to me, and I’ll get started right away!
