### ISSUE TITLE
Hamburger button in the navabar

### ISSUE THREAD

**Issue by SatyaJaiss** [arjunatapadkar/codeteria#21]
![Screenshot 2024-10-02 224530](https://github.com/user-attachments/assets/69349561-2dd3-4b07-8d19-1308451693c6)

Hamburger button is needed in the navbar for the elements

@arjunatapadkar kindly assign it to me, I'll fix it shortly

**Comment by itznayan** [comment]
@arjunatapadkar  please assign this issue to me .

**Comment by itznayan** [comment]
@arjunatapadkar ,please approve PR. i have fixed this issue
