### ISSUE TITLE
ENHANCEMENT|| Redesign the Landing page Crousel

### ISSUE THREAD

**Issue by shubhagarwal1** [arjunatapadkar/codeteria#211]
- utilise full width with crousel 
- revamp cards add some badeges to the cards 
<img width="1440" alt="Screenshot 2024-10-21 at 5 41 24 AM" src="https://github.com/user-attachments/assets/05c45707-a49d-46c6-9275-b6989d9ef90e">

**Comment by arjunatapadkar** [comment]
You have to add video after completion and then will decide whether to merge it or not 

Will merge only if I feel it's better than current one
