### ISSUE TITLE
 Revamp complete homepage

### ISSUE THREAD

**Issue by shubhagarwal1** [arjunatapadkar/codeteria#226]
<img width="1425" alt="Screenshot 2024-10-23 at 6 40 52 AM" src="https://github.com/user-attachments/assets/f05267f8-6f16-4b9d-9dc2-ad904612c2e4">

Hey @arjunatapadkar pleaase assign me this task, also plese mention some design details you expect to see.

**Comment by arjunatapadkar** [comment]
Use some darkish colours and ui should be better than current one 

You can change or add other cards, sections, layouts or anything related to concept of website
