### ISSUE TITLE
bug : try it yourself button in cheatsheets

### ISSUE THREAD

**Issue by arjunatapadkar** [arjunatapadkar/codeteria#244]
Change the default CPP implementation to language based or completely remove default cpp 

remove default  - level 1
language based - level 3

![Screenshot (267)](https://github.com/user-attachments/assets/4115c8ef-7b38-4014-a36d-e11f689df1b9)

![Screenshot (266)](https://github.com/user-attachments/assets/6131b36a-e1ec-4c6e-8bdf-3c5bac99a692)

**Comment by arjunatapadkar** [comment]
@ParasY1724   ??

**Comment by ParasY1724** [comment]
@arjunatapadkar ok i will work on it.

**Comment by ParasY1724** [comment]
@arjunatapadkar can you add some java & javascript snippets ,  i am done with implementation but still wanna test .
Only one small Hello World Snippet of each be enough

**Comment by arjunatapadkar** [comment]
Give me some time. I will do it within 1  hour. 

At least it should select the correct language. And it's not necessary to check and reformat to executable as I will make sure to add executable code snippets.

**Comment by arjunatapadkar** [comment]
Done @ParasY1724

**Comment by ParasY1724** [comment]
@arjunatapadkar Check this out
I made it language based + you can change language if you want from menu 

https://github.com/user-attachments/assets/d2e9e0de-3a83-4524-825a-47d0cd929f6e


# But Java has a Issue , Code gets execute when and only it has outer class as Main

https://github.com/user-attachments/assets/fe095e59-9399-4b40-9a30-311a271cc40b

# You would change the snippets or i shall handle it ??

**Comment by arjunatapadkar** [comment]
It's okay I will create accordingly
