### ISSUE TITLE
Fixing dsproblem page design & Adding Detailed Page for dsproblem

### ISSUE THREAD

**Issue by ParasY1724** [arjunatapadkar/codeteria#265]
**Description:**
After Clicking Read More on dsproblem no page is created for this thus 404 not found ;
![Screenshot From 2024-10-29 18-49-44](https://github.com/user-attachments/assets/9ca049c3-ebec-4452-afba-79973cffe3b2)
![Screenshot From 2024-10-29 18-49-55](https://github.com/user-attachments/assets/80c15f34-21bd-4ed9-aa5b-71b52e5e650a)

**I would like to create  Detailed Page similar to leetcode  & integrate it with same compiler used in playground**

**Comment by ParasY1724** [comment]
@arjunatapadkar please assign this task to me

**Comment by arjunatapadkar** [comment]
In that api response all the data is available like - statement, description, inputs, outputs, code for brute force and optimal, etc. And dsproblem page only shows titles from response. 

Check the api response and create accordingly

And give the basic idea before implementing

**Comment by ParasY1724** [comment]
@arjunatapadkar hello sir , i have been implementing the page i have one request :
Although Backend API gives 
` "IO": [
        {
          "_id": "66e00c5adc1b019d344e2676",
          "input": "word1 = \"abc\", word2 = \"pqr\"",
          "output": " \"apbqcr\"",
          "__v": 0
        }, .... ]`
        
 **Could you please add one more field like**

`
"testcases" : [
{
"input" : "abc\npqr",
"expected" : "apbqcr"
},
]
`
**without double quotes**  like codechef or leetcode , so that i could easily add them in testcase section , have a look
![Screenshot From 2024-10-30 19-46-41](https://github.com/user-attachments/assets/ed9586ec-6cf1-446b-918b-2b8757f32ef9)

# For Now Ignore my UI/UX  but these is my progress so far :

https://github.com/user-attachments/assets/f0987cbb-e402-44ef-87bb-3912fc0d0acd



there is more to add like company labels , etc

**Comment by arjunatapadkar** [comment]
Is it possible to use IO for testcases??

**Comment by arjunatapadkar** [comment]
If it's required will do it tomorrow morning

**Comment by ParasY1724** [comment]
> Is it possible to use IO for testcases?? 

Well , yes it is then for every IO there should be '=' then i can just take value after = . I can proceed with that. 👍

**Comment by ParasY1724** [comment]
@arjunatapadkar i am getting no token provided for endpoint:
https://codeteria-backend.vercel.app/api/v1/dsproblem

**Comment by arjunatapadkar** [comment]
check it now @ParasY1724
