### ISSUE TITLE
Adding About Us page

### ISSUE THREAD

**Issue by AswaniBolisetti** [arjunatapadkar/codeteria#282]
@arjunatapadkar 
Currently the website lacks about us page, I would like to work on it
Kindly assign it to me

**Comment by arjunatapadkar** [comment]
its not planned yet so you can look for some other issues @AswaniBolisetti

**Comment by AswaniBolisetti** [comment]
> its not planned yet so you can look for some other issues @AswaniBolisetti

Okay
Thank you
