### ISSUE TITLE
The community page leads to error 404, instead lead to coming soon

### ISSUE THREAD

**Issue by avogadroB** [arjunatapadkar/codeteria#284]
since the Community Page leads to not found, you cannot navigate back using the navigation bar.

## what it is:
![image](https://github.com/user-attachments/assets/88cfdf9b-189c-4e84-81ff-a5a2c61681ff)

## what it should be:
![image](https://github.com/user-attachments/assets/8a942f80-baa2-457d-a6d8-7ffc9fadf0cd)

**Comment by ketansahugit** [comment]
@avogadroB  Done
