### ISSUE TITLE
The UI/UX of the login page needs to be improved

### ISSUE THREAD

**Issue by avogadroB** [arjunatapadkar/codeteria#285]
Make this better:
![image](https://github.com/user-attachments/assets/6249842b-1dd5-4fa5-b4ee-c7436e0dfacf)

**Comment by avogadroB** [comment]
thanks for assigning this to me

**Comment by avogadroB** [comment]
@arjunatapadkar hey, there is no login option on the page using the newest repo, is it fine if i make a new login page and add login to the navbar?

**Comment by arjunatapadkar** [comment]
Create a page but don't add to navbar
