### ISSUE TITLE
 Enhanced scroll back button with timeline on it for smoother functioning.

### ISSUE THREAD

**Issue by shriyadindi** [arjunatapadkar/codeteria#294]
Enhanced scroll back button with timeline on it for smoother functioning.
![Screenshot 2024-10-31 115055](https://github.com/user-attachments/assets/03f414dc-91e7-4719-b69c-8cc93f8ae128)

**Comment by veepanshu-kasana** [comment]
@arjunatapadkar I want to contribute to this project on this particular issue. Please assign it to me!
