### ISSUE TITLE
Program Cards Updates and Programming Lables Scroll Update

### ISSUE THREAD

**Issue by rajatsinghal02** [arjunatapadkar/codeteria#30]
This site is looks good.The UI is beautiful I have encountered some issue is the coding page and want to update the card of that page with proper spacing and the lables attached.

![Screenshot_20241003_131234.jpg](https://github.com/user-attachments/assets/67060233-ccee-4144-b63f-e46fddbd2911)

@arjunatapadkar Please assign this issue to me. I want to work to resolve this issue.

**Comment by rajatsinghal02** [comment]
@arjunatapadkar Please add hacktoberbest lable also.

**Comment by arjunatapadkar** [comment]
before raising pr, post snapshots firstly in both mobile and desktop mode

**Comment by rajatsinghal02** [comment]
![Desktop_Output](https://github.com/user-attachments/assets/0eade506-2fff-4928-bf43-030e5574ff67)
![Mobile_output](https://github.com/user-attachments/assets/c854e60d-6df2-41f3-ad00-3473950616bb)

@arjunatapadkar I have update the programs card for mobile and desktop view please check so that I am raising the pr
