### ISSUE TITLE
Updating the navbar

### ISSUE THREAD

**Issue by NK-Works** [arjunatapadkar/codeteria#33]
![image](https://github.com/user-attachments/assets/cd781360-a986-44c3-b009-d9369b27deea)
The navbar here doesn't look goof...
I can update it...
make sure to add the logos...
thanks:)

**Comment by arjunatapadkar** [comment]
@NK-Works give me some demo or idea that exactly what you will create

**Comment by NK-Works** [comment]
@arjunatapadkar I can make the navbar there similar to the one on the main page so as to maintain consistency...
Or maybe if you want a redesign of the entire navbar for all the pages thats also possible but that will kinda mismatch with the overall theme of the website... purple hue with yellow effects....
