### ISSUE TITLE
Improve cheats page

### ISSUE THREAD

**Issue by prasoonk1204** [arjunatapadkar/codeteria#34]
The code snippet area of cheats page is in white color even in dark mode, I would like to make it darker to go well with the theme.
Also, the color of the headings in cheats page is bit too dark shade for dark mode.

I would like to work on this.. please assign it to me
also add _gssoc-ext_, _hactoberfest-accepted_ and _level (1/2/3_ -- based on what you think is the difficulty of this task) labels.

![Screenshot 2024-10-03 183200](https://github.com/user-attachments/assets/2ee09db6-3300-49c1-ad10-dbe9f711e581)

**Comment by arjunatapadkar** [comment]
Go ahead 👍

**Comment by prasoonk1204** [comment]
thanks for assigning it to me.. can you please add **_hacktoberfest-accepted_** label as well

**Comment by prasoonk1204** [comment]
Hey, I was still working on this issue and saw that you closed it, do i still need to work on this? I haven't even done my PR, why did you close the issue, if i may get to know about that?

**Comment by arjunatapadkar** [comment]
Ohh, accidentally closed

**Comment by prasoonk1204** [comment]
I am facing an issue while opening the cheats page in my local machine, it's stuck on loading.
Can you help me a little with that?

![IMG-20241004-WA0030](https://github.com/user-attachments/assets/bdd761ce-093d-42bb-8b6d-5c073d1c44a9)
