### ISSUE TITLE
Redesign the landing page 

### ISSUE THREAD

**Issue by arjunatapadkar** [arjunatapadkar/codeteria#40]
Redesign the color theme of landing page with heavy animations, transitions and should be modern, sleek and visually appealing 

Anybody can work on this and will merge the pr which is more visually appealing

**Comment by arjunatapadkar** [comment]
While raising the pr make sure to mention issue number #

**Comment by 4F24L** [comment]
Can you assign me this issue !!

**Comment by Sourabh782** [comment]
@arjunatapadkar Can i work on this?

**Comment by SaanyaGarg5** [comment]
You can assign me this task under gsssoc and hacktoberfest level 3 label.

**Comment by shreyamaheshwari1** [comment]
@arjunatapadkar can you assign me this too under hactoberfest and gssoc extended labels? I'll also try to make this look more applealing .

**Comment by shreyamaheshwari1** [comment]
Hii @arjunatapadkar the landing page component in your codebase just includes the navbar do you only need it to be modified??

**Comment by arjunatapadkar** [comment]
Change the color scheme and animations of landing page itself and you can change the layout as well. 

Do whatever you want but should be relatable and more attractive than current one 

match the navbar according to the color scheme 


You can create this in multiple PRs in order to get more points 👍

But will merge only if I find out better than current one
