### ISSUE TITLE
add contact us / review at footer

### ISSUE THREAD

**Issue by ananyag309** [arjunatapadkar/codeteria#47]
it will be great if we allow user to contact or review the project which will help to connect and improve our project further 
![footer](https://github.com/user-attachments/assets/bc092dc8-0d3c-4b4f-b60e-19c890a28a05)

**Comment by arjunatapadkar** [comment]
Sounds good

**Comment by ananyag309** [comment]
@arjunatapadkar please assign it to me under gssoc  ext and hacktoberfest
