### ISSUE TITLE
UI/UX Redesign for Improved Playground Interface

### ISSUE THREAD

**Issue by theamrendram** [arjunatapadkar/codeteria#49]
**Description:**
The current interface serves its functional purpose but could benefit from a redesign to improve the overall user experience and visual appeal. The goal is to implement a more modern, intuitive, and responsive design.

**Proposed Changes:**
-   Update the colour scheme for better readability and contrast.
-   Redesign interactive elements (buttons, dropdowns) for a more intuitive user experience.
-   Enhance the code editor with better syntax highlighting and usability features (e.g., line numbers).
-   Improve the output window layout for better visibility and feedback.

Please assign this issue to me under GSSoC. 
<img width="1669" alt="Screenshot 2024-10-04 at 8 01 55 PM" src="https://github.com/user-attachments/assets/d4e87032-8a0a-43d8-88e9-e4f59fd1c542">

**Comment by arjunatapadkar** [comment]
@KumarAmrendram  make sure to add snapshots/video with pr to get merged quickly

**Comment by theamrendram** [comment]
Thanks for the heads-up! I'll make sure to include the snapshots and video with the PR.
