### ISSUE TITLE
slider for reviews section, animated effects for cards 

### ISSUE THREAD

**Issue by Slambot01** [arjunatapadkar/codeteria#5]
slider to be added to the review section of people and also the rotating animation of the card symbols  need to be updated in order to make it more decent

**Comment by Slambot01** [comment]
thanks for assigning me

**Comment by arjunatapadkar** [comment]
@Slambot01 do it quickly otherwise will assign the issue to someone else

**Comment by arjunatapadkar** [comment]
Anybody can work on this and will merge on basis of quality

**Comment by Slambot01** [comment]
can u pls assign me i have worked on it and i have to push the code
