### ISSUE TITLE
UI/UX Redesign for Improved cheats Interface for dark mode as well as fix for non-functioning footer 

### ISSUE THREAD

**Issue by abhishekpanthee** [arjunatapadkar/codeteria#52]
Description:
The cheats section for dark mode is not visually appealing  as well as the footer links only redirects to the active page despite of its description also there are different form of footers for upcoming and some sections which is an unneeded feature .

Proposed Changes:

Fix the UI to make visually appealing  for dark mode 
Working clickable redirects or navigation from footer to the descriptive section
One in all footer for every section that include all the desired sections to navigate

**Comment by arjunatapadkar** [comment]
@abhishekpanthee make sure to add snapshots/video with pr to get merged quickly
