### ISSUE TITLE
Buttons in 'Interactive Code Playground' shift based on text length

### ISSUE THREAD

**Issue by Hamza20203064** [arjunatapadkar/codeteria#6]
In the ***'Interactive Code Playground,'*** the buttons shift or move depending on the length of the text between them. This results in inconsistent alignment and may affect user experience when interacting with the playground. The expected behavior is for the buttons to remain in a fixed position regardless of the text content to maintain a clean and consistent layout.

https://github.com/user-attachments/assets/9a3a1774-b520-4985-929c-debf06e90b9f

If this issue is assigned to me under GSSoC-Extd, it would be my pleasure to contribute to it.

**Comment by arjunatapadkar** [comment]
@Hamza20203064  Make sure to add demo while raising pr to get merged quickly

**Comment by Hamza20203064** [comment]
ok, I will do that

**Comment by Hamza20203064** [comment]
After fixing the issue:

https://github.com/user-attachments/assets/7d2873b6-ae6c-4822-a22b-8b61abdaf89d

@arjunatapadkar

**Comment by arjunatapadkar** [comment]
@Hamza20203064 Great 👍
