### ISSUE TITLE
Social Media Handles Buttons can be Added

### ISSUE THREAD

**Issue by Harshgupta88156** [arjunatapadkar/codeteria#61]
![Screenshot 2024-10-05 184630](https://github.com/user-attachments/assets/ae524403-a890-4529-a821-7c80386b7b1d)

Footer looks quietly impressive but we can social media handles handles i.e. X, instagram,linkedin etc for more engagement!!!
@PA please assign me this project under GSSOC extd and hactoeberfest program !!!
i will surely rectify it and make it more valuable!!!!

**Comment by Harshgupta88156** [comment]
![Screenshot 2024-10-07 153701](https://github.com/user-attachments/assets/96e40474-5ece-4f39-8560-11285bf9bc40)
i am not getting access to push my branch!!
![Screenshot 2024-10-07 150734](https://github.com/user-attachments/assets/8a020b2a-0fe3-43fa-9125-a07f336ea2c8)
i have modified this in the footer section>> how can i push!!

**Comment by arjunatapadkar** [comment]
Don't push it 
Create a pull request
