### ISSUE TITLE
[Feature] Implement User Authentication and Set Up Backend

### ISSUE THREAD

**Issue by Dev-Rishav** [arjunatapadkar/codeteria#62]
**Description:**

I noticed that you're planning to introduce a community page and premium features for users. To ensure a seamless and personalized experience, implementing user authentication is critical for managing preferences and securing access to premium content.

**Proposed Solution:**

 1.  **Backend Setup**: Initialize the backend using Node.js, Express.js, and MongoDB.
2.  **User Authentication**: Implement JWT-based authentication for secure user login and session management.
3.  **Protected Routes**: Establish protected routes to restrict access to authenticated users.
 4.  **User Data Management**: Add new users to the MongoDB collection with the necessary attributes for forum participation and premium feature management.

If everything looks good, kindly proceed with assigning the issue under the relevant GSSoC extended labels. Thank You!

**Comment by arjunatapadkar** [comment]
@Dev-Rishav backend is not under gssoc
