### ISSUE TITLE
Upcoming Section

### ISSUE THREAD

**Issue by Jahsid** [arjunatapadkar/codeteria#64]
![Screenshot 2024-10-06 020841](https://github.com/user-attachments/assets/719ed8b1-6454-47db-aceb-8b805d6de459)
@arjunatapadkar Can you assign to me?

**Comment by arjunatapadkar** [comment]
@Jahsid what  are you going to do?

**Comment by Jahsid** [comment]
@arjunatapadkar My idea is to add basic, intermediate, and advanced articles on React.js. If you have any suggestions, I would be happy to consider them

**Comment by arjunatapadkar** [comment]
It's actually a backend part but you can create a page with dummy data, backend is not under gssoc
