### ISSUE TITLE
Create a Responsive "Get in Touch" / "Contact Us" Section

### ISSUE THREAD

**Issue by Rahul-AkaVector** [arjunatapadkar/codeteria#75]
![{44F4B565-1D9C-4A0B-BBA5-66654B9134B2}](https://github.com/user-attachments/assets/70107082-32e9-4ef8-9aa2-bc1b4678ef16)

**Issue: Create a Responsive "Get in Touch" / "Contact Us" Section**

**Description:**
I'd like to take responsibility for designing and implementing a responsive "Get in Touch" or "Contact Us" section to be placed at the bottom of the home page. This section should be mobile-friendly and aligned with the overall design of the website. Please assign this task to me.

**Why is this needed?**
A responsive contact section is essential for improving user interaction and accessibility, particularly on mobile devices. It will also make the site more user-friendly and professional.

**Assignee:**
Rahul Aka Vector 
@arjunatapadkar

**Comment by roushan-code** [comment]
**Hi @arjunatapadkar, Can I work on it?**
