### ISSUE TITLE
Add User Profile Page

### ISSUE THREAD

**Issue by iamsohelx** [arjunatapadkar/codeteria#76]
**Description**

Hey @arjunatapadkar In your website we can add a user profile page, in which user can se his/her details after login.
Name:
email:
username:
and etc....

i wanted to create a Login Page + Sign Up Page + Profile Page [ Frontend + Backend ]
And Add Database where users data will be stored.

**Comment by iamsohelx** [comment]
Hey @arjunatapadkar I can help you to do this. could you please assign this task to me.

**Comment by arjunatapadkar** [comment]
@iamsohelx  Backend is not open sourced

**Comment by iamsohelx** [comment]
@arjunatapadkar Can I make only frontend?
