### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by shreya-paul-17** [arjunatapadkar/codeteria#77]
Dear Project Admin @arjunatapadkar ,

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by arjunatapadkar** [comment]
@shreya-paul-17 repository is under gssoc only and the corresponding labels with levels are given to the issues

**Comment by shreya-paul-17** [comment]
@arjunatapadkar For hacktoberfest you dont have to register anywhere, PAs only need to add Hacktoberfest topic in their repository.
And since gssoc projects are part of hacktoberfest I tell you to add hacktoberfest accepted label.

**Comment by arjunatapadkar** [comment]
@shreya-paul-17 sure

**Comment by shreya-paul-17** [comment]
@arjunatapadkar Also add the label to the merged PRs

**Comment by arjunatapadkar** [comment]
@arjunatapadkar Sure 👍

**Comment by arjunatapadkar** [comment]
@shreya-paul-17 sure 👍
