### ISSUE TITLE
In the interview preparation section react.js docs not found 

### ISSUE THREAD

**Issue by adityalaxkar123** [arjunatapadkar/codeteria#79]
I would like to work on the react.js docs for interview preparation in the interview section 
![IMG_20241007_131221](https://github.com/user-attachments/assets/50e6c1e3-978d-4afa-a557-020ecd152673)

**Comment by adityalaxkar123** [comment]
Me a GSSOC'24 extended member can you assign it to me

**Comment by arjunatapadkar** [comment]
Actually it has backend for this
