### ISSUE TITLE
Community Forum

### ISSUE THREAD

**Issue by RiyaJain8114** [arjunatapadkar/codeteria#81]
Community Forum
Contribution Idea: Build a community forum for users to ask questions, share knowledge, and discuss coding topics.
Implementation: Include features like thread creation, commenting, and upvoting responses.

**Comment by arjunatapadkar** [comment]
It will require some backend stuff right??
The backend repository is not under gssoc and it's private
@RiyaJain8114

**Comment by RiyaJain8114** [comment]
ok got it .  can we add UI buttons to allow users to upvote or downvote responses or comments (without backend integration).
and display the current vote count.

**Comment by arjunatapadkar** [comment]
Upvotes for what? Means, I'm not getting what are you trying to explain.

@RiyaJain8114

**Comment by RiyaJain8114** [comment]
upvote are similar to like responses, comments, or content that they find useful or agree with

**Comment by RiyaJain8114** [comment]
![image](https://github.com/user-attachments/assets/8ef936ae-8b60-4b43-b120-77188ced8088)
something like this

**Comment by arjunatapadkar** [comment]
I know what upvotes are but I'm asking where to use it because there is no community forum.

So what do think where it will be useful  in our project @RiyaJain8114

**Comment by arjunatapadkar** [comment]
The community forum feature is not yet planned?
