### ISSUE TITLE
Including Share option

### ISSUE THREAD

**Issue by PoojaKanagaraj06** [arjunatapadkar/codeteria#82]
I am willing to add share option to the web page so that user can share the website to their friends and surroundings and can have use more people to the choosed social media
![image](https://github.com/user-attachments/assets/a1094b98-58c8-4e7f-9f46-4f22418cc74d)
kindly assign the work to me @arjunatapadkar as per the tag gssoc'24 Extd.

**Comment by arjunatapadkar** [comment]
Add snapshots or video along with pr

**Comment by PoojaKanagaraj06** [comment]
Sure @arjunatapadkar
