### ISSUE TITLE
Including Rating stars

### ISSUE THREAD

**Issue by PoojaKanagaraj06** [arjunatapadkar/codeteria#83]
I am willing to work on including the Rating star option so that we can easily get the feed back of users, with some emojies reacting as per the ratings.
kindly assign the work to me @arjunatapadkar as per the label gssoc'24 extd 
![image](https://github.com/user-attachments/assets/e57ae51d-9208-4d28-9da1-3f642e9195d9)
like the above image

**Comment by arjunatapadkar** [comment]
It will require some backend stuff right??
Backend repository is not under gssoc and it's private actually @PoojaKanagaraj06

**Comment by PoojaKanagaraj06** [comment]
Yes @arjunatapadkar I actually thought to create a feed back of star only at front end by the use of html and css, for attracting users.

**Comment by arjunatapadkar** [comment]
Are you familiar with React.js? Will recommend to create it using Reactjs @PoojaKanagaraj06

**Comment by PoojaKanagaraj06** [comment]
Yes I am familiar to react.js @arjunatapadkar I will make it out using react.js

**Comment by arjunatapadkar** [comment]
Sure @PoojaKanagaraj06

**Comment by raj-adi00** [comment]
@arjunatapadkar can you assign it to me under hacktoberfest and gssoc
