### ISSUE TITLE
redesigning of "Interview prep" page

### ISSUE THREAD

**Issue by isimarjitsingh** [arjunatapadkar/codeteria#88]
as your interview prep page quiet good but i think i able to do it more interactive like giving it some extra properties which will gonna give it a professional look so please assign me this work .GSSOC EXTD

![Screenshot 2024-10-07 232419](https://github.com/user-attachments/assets/0d005d21-cebe-4026-895e-41c5ebae9b9a)

**Comment by SaanyaGarg5** [comment]
You can assign me this task under gsssoc and hacktoberfest level 3 label.
