### ISSUE TITLE
[FEATURE UPGRADE] : Footer  connect section can be improved.

### ISSUE THREAD

**Issue by Amarjha01** [arjunatapadkar/codeteria#92]
**Title**
Imlimenting clickable connect info.

#New Feature
Clickable link to footer contect section.

## Description
Clickable link to footer connect section so that user can easily navigate or view location and when user click on email that will redirect to mail .

## Steps to Implement 

1 . using google map API 
2. using  mailto protocol

**Screenshot **

![image](https://github.com/user-attachments/assets/10aed293-355f-4da6-9062-ce4357019f80)

@arjunatapadkar I would like to work on this.

**Comment by itznayan** [comment]
hey @arjunatapadkar ,please assign this issue to me.
