### ISSUE TITLE
Scroll to top button not hidding on top of the page

### ISSUE THREAD

**Issue by tarunkumar2005** [arjunatapadkar/codeteria#99]
When i am already on top part of the page didn't scrolled then the scroll to top button should be hidden but it is showing.

![image](https://github.com/user-attachments/assets/e0608d97-8c7d-42b3-8855-633458b45e45)

@arjunatapadkar Assign this to under gssoc 2024 ext and hacktoberfext i would like to work on this issue.

**Comment by tarunkumar2005** [comment]
@arjunatapadkar I tried to do it but can't fix it give it to someone else it is not detecting the scrolling i don't know why i think it is because of framer-motion so can't fix this thing i worked on it for 3 hours but can't find a fix for it sorry.

**Comment by arjunatapadkar** [comment]
@tarunkumar2005 it's okay, at least you tried. Keep exploring.
